//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CleanupStuckPolicy) DeepCopyInto(out *CleanupStuckPolicy) {
	*out = *in
	out.StuckAfter = in.StuckAfter
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CleanupStuckPolicy.
func (in *CleanupStuckPolicy) DeepCopy() *CleanupStuckPolicy {
	if in == nil {
		return nil
	}
	out := new(CleanupStuckPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CronExecutionCleaner) DeepCopyInto(out *CronExecutionCleaner) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CronExecutionCleaner.
func (in *CronExecutionCleaner) DeepCopy() *CronExecutionCleaner {
	if in == nil {
		return nil
	}
	out := new(CronExecutionCleaner)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CronExecutionCleaner) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CronExecutionCleanerList) DeepCopyInto(out *CronExecutionCleanerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CronExecutionCleaner, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CronExecutionCleanerList.
func (in *CronExecutionCleanerList) DeepCopy() *CronExecutionCleanerList {
	if in == nil {
		return nil
	}
	out := new(CronExecutionCleanerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CronExecutionCleanerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CronExecutionCleanerSpec) DeepCopyInto(out *CronExecutionCleanerSpec) {
	*out = *in
	out.Retain = in.Retain
	out.CleanupStuck = in.CleanupStuck
	out.RunInterval = in.RunInterval
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CronExecutionCleanerSpec.
func (in *CronExecutionCleanerSpec) DeepCopy() *CronExecutionCleanerSpec {
	if in == nil {
		return nil
	}
	out := new(CronExecutionCleanerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CronExecutionCleanerStatus) DeepCopyInto(out *CronExecutionCleanerStatus) {
	*out = *in
	if in.LastRunTime != nil {
		in, out := &in.LastRunTime, &out.LastRunTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CronExecutionCleanerStatus.
func (in *CronExecutionCleanerStatus) DeepCopy() *CronExecutionCleanerStatus {
	if in == nil {
		return nil
	}
	out := new(CronExecutionCleanerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RetentionPolicy) DeepCopyInto(out *RetentionPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RetentionPolicy.
func (in *RetentionPolicy) DeepCopy() *RetentionPolicy {
	if in == nil {
		return nil
	}
	out := new(RetentionPolicy)
	in.DeepCopyInto(out)
	return out
}
